Update numpy.py
Fix overflow seen on Windows.

error:  tf.constant(0x80000000, dtype=tf.int32),
OverflowError: Python int too large to convert to C long